default: &default
  adapter: mysql2
  encoding: utf8
  database: default
  username: markrds01
  password: dbpass01
  host: marks-rds-mysql.clbd4orl1iyi.us-east-1.rds.amazonaws.com
  port: 3306

development:
  adapter: mysql2
  encoding: utf8
  database: development
  username: markrds01
  password: dbpass01
  host: marks-rds-mysql.clbd4orl1iyi.us-east-1.rds.amazonaws.com
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: test
  username: markrds01
  password: dbpass01
  host: marks-rds-mysql.clbd4orl1iyi.us-east-1.rds.amazonaws.com
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: production
  username: markrds01
  password: dbpass01
  host: marks-rds-mysql.clbd4orl1iyi.us-east-1.rds.amazonaws.com
  port: 3306


